[package]
name = "sfu"
version = "0.0.0"
authors = ["Rusty Rain <y@ngr.tc>"]
edition = "2021"
description = "A pure Rust implementation of SFU"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/sfu"
repository = "https://github.com/webrtc-rs/sfu"
homepage = "https://sfu.rs"
keywords = ["networking", "protocols"]
categories = [ "network-programming", "asynchronous" ]

[dependencies]
retty = "0.26.0"
bytes = "1.5.0"
log = "0.4.20"
base64 = "0.21.5"
rand = "0.8.5"
rcgen = { version = "0.11", features = ["pem", "x509-parser"] }
ring = "0.17.7"
sha2 = "0.10.8"
rustls = "0.21.7"

# RTC protocols
shared = { path = "rtc/shared"}
sdp = { path = "rtc/sdp"}
stun = { path = "rtc/stun"}
rtp = { path = "rtc/rtp"}
rtcp = { path = "rtc/rtcp"}
srtp= { path = "rtc/srtp"}
dtls = { path = "rtc/dtls"}
sctp = { path = "rtc/sctp"}
data = { path = "rtc/data"}

[dev-dependencies]
futures = "0.3.30"
smol = "2.0.0"
tokio = { version = "1.24.1", features = ["fs", "rt-multi-thread", "macros", "signal"] }
tokio-util = "0.7.10"
hyper = { version = "0.14.16", features = ["full"] }
chrono = "0.4.31"
env_logger = "0.10.1"
clap = { version = "4.4.12", features = ["derive"] }
anyhow = "1.0.78"
ctrlc = "3.4.2"
async-broadcast = "0.6.0"
waitgroup = "0.1.2"
thiserror = "1.0.53"
core_affinity = "0.8.1"
num_cpus = "1.16.0"

[[example]]
name = "chat"
path = "examples/chat.rs"
test = false
bench = false
