[package]
name = "sfu"
version = "0.0.0"
authors = ["Rusty Rain <y@ngr.tc>"]
edition = "2021"
description = "A pure Rust implementation of SFU"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/sfu"
repository = "https://github.com/webrtc-rs/sfu"
homepage = "https://sfu.rs"
keywords = ["networking", "protocols"]
categories = ["network-programming", "asynchronous"]

[dependencies]
retty = "0.24.0"
bytes = "1.5.0"
log = "0.4.20"
base64 = "0.21.5"
serde = "1.0.193"
serde_json = { version = "1.0.111", features = [] }
rand = "0.8.5"
rcgen = { version = "0.11", features = ["pem", "x509-parser"] }
ring = "0.17.7"
sha2 = "0.10.8"
rustls = "0.21.7"
url = { version = "2", features = [] }
hex = { version = "0.4.3", features = [] }

# RTC protocols
shared = { path = "rtc/shared" }
sdp = { path = "rtc/sdp" }
stun = { path = "rtc/stun" }
rtp = { path = "rtc/rtp" }
rtcp = { path = "rtc/rtcp" }
srtp = { path = "rtc/srtp" }
dtls = { path = "rtc/dtls" }
sctp = { path = "rtc/sctp" }
data = { path = "rtc/data" }

[dev-dependencies]
# sfu impl
clap = { version = "4.4.12", features = ["derive"] }
anyhow = "1.0.78"
wg = "0.7"
crossbeam-channel = "0.5.11"
ctrlc = "3.4.2"

# str0m impl
rouille = { version = "3.6.2", features = ["ssl"] }
systemstat = "0.2.2"

# tests
webrtc = { path = "webrtc/webrtc" }
tokio = { version = "1.36", features = ["full"] }
tokio-util = "0.7"
chrono = "0.4"
env_logger = "0.11"
hyper = { version = "0.14.28", features = ["full"] }

[[example]]
name = "sync_chat"
path = "examples/sync_chat.rs"
test = false
bench = false
