[package]
name = "sfu"
version = "0.0.0"
authors = ["Rusty Rain <y@liu.mx>"]
edition = "2021"
description = "A pure Rust implementation of WebRTC SFU"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/sfu"
repository = "https://github.com/ngr-tc/sfu"
homepage = "https://sfu.rs"
keywords = ["networking", "protocols"]
categories = [ "network-programming", "asynchronous" ]

[dependencies]
bytes = "1.3.0"
log = "0.4.17"
retty = { version = "0.4.1", features = ["runtime-tokio"] }

[dev-dependencies]
clap = { version = "4.1.1", features = ["derive"] }
chrono = "0.4.23"
env_logger = "0.10.0"
