[package]
name = "sfu"
version = "0.0.0"
authors = ["Rusty Rain <y@liu.mx>"]
edition = "2021"
description = "A pure Rust implementation of SFU"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/sfu"
repository = "https://github.com/ngr-tc/sfu"
homepage = "https://sfu.rs"
keywords = ["networking", "protocols"]
categories = [ "network-programming", "asynchronous" ]

[dependencies]
retty = { version = "0.15.3", features = ["runtime-tokio"] }
tokio = { version = "1.24.1", features = ["rt-multi-thread", "macros", "signal"] }
hyper = { version = "0.14.16", features = ["full"] }
clap = { version = "4.1.1", features = ["derive"] }
async-trait = "0.1.61"
bytes = "1.3.0"
log = "0.4.17"
chrono = "0.4.23"
env_logger = "0.10.0"
anyhow = "1.0.68"

[[bin]]
name = "sfu"
path = "src/bin/sfu.rs"
test = false
bench = false
