codecov:
  require_ci_to_pass: yes
  max_report_age: off
  token: 6c7bd236-98cc-432f-8d35-1fd7b41c7b1a

coverage:
  precision: 2
  round: down
  range: 50..90
  status:
    project:
      default:
       enabled: no
       threshold: 0.2
       if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
